### ISSUE TITLE
NaughtyAttributes don't work on custom Inspector Editors

### ISSUE THREAD

**Issue by mattnewport** [dbrizov/NaughtyAttributes#17]
Normally if I define a custom PropertyDrawer with an Attribute and apply that Attribute to a field for a MonoBehaviour that has a Custom Inspector and I use `EditorGUILayout.PropertyField(field);` do draw that field in the Custom Inspector's `OnInspectorGUI()` then the custom PropertyDrawer will still be used for that field in the Custom Inspector. 

If I apply a NaughtyAttributes Attribute like `ShowIf` to a field in a MonoBehaviour then it draws as expected with the Default Inspector but if I have a Custom Inspector and draw that field with `EditorGUILayout.PropertyField()` it won't use the custom NaughtyAttributes PropertyDrawer. Is there any way to get this to work inside a Custom Inspector?

**Comment by dbrizov** [comment]
I have to check that out mate, but I don't think it's possible at the moment.

**Comment by mattnewport** [comment]
The way I usually use this in a Custom Inspector is something like this:
```
void OnEnable()
{
    ...
    prop = serializedObject.FindProperty("prop");
    ...
}

public override void OnInspectorGUI()
{
    ...
    EditorGUILayout.PropertyField(prop);
    ...
}
```
So I'd be fine with doing something like:
```
public override void OnInspectorGUI()
{
   ...
   NaughtyAttributes.GUILayout.PropertyField(prop);
   ...
}
```
If that's easier to get working. Just as long as there's some way to get the custom drawing from a Custom Inspector, it doesn't have to be via `EditorGUILayout.PropertyField()`.

**Comment by mattnewport** [comment]
The first Attribute I used and the one I had problems with was `ShowIf` - it could be that some of the others work fine and that just happens to be one of the ones that doesn't.

**Comment by overdub** [comment]
Hope this is not off topic: 
Only an incomplete solution, but I managed to get Attributes working in my custom editor by using NaughtyAttributes.InspectorEditor as base class. Only thing is that I needed to make InspectorEditor.OnEnable "protected virtual" so I could override.
In my custom editor I override OnInspectorGUI and do what I need after base.OnInspectorGUI().

**Comment by themorfeus** [comment]
> Hope this is not off topic:
> Only an incomplete solution, but I managed to get Attributes working in my custom editor by using NaughtyAttributes.InspectorEditor as base class. Only thing is that I needed to make InspectorEditor.OnEnable "protected virtual" so I could override.
> In my custom editor I override OnInspectorGUI and do what I need after base.OnInspectorGUI().

This works, although it would be helpful to mark OnEnable and OnDisable as protected virtual, so that they can be overriden in inheriting inspectors.

**Comment by dbrizov** [comment]
Fixed in version 2.0.0.
The attributes are now reimplemented with Unity's CustomPropertyDrawer so they work in custom inspectors. There are some exceptions, however (like ReorderableList, EnableIf...). For these to work you need to call `NaughtyEditorGUI.PropertyField_Layout` instead of `EditorGUILayout.PropertyField` when you are creating your custom editors

**Comment by celojevic** [comment]
This problem still exists when making a custom editor like the latest answer by Bgbg in this link: http://answers.unity.com/answers/1904868/view.html

[ReadOnly] and [ShowIf] attributes dont draw as expected
